#!/bin/bash

base_url="https://ynetnews.com/"
site="https://ynetnews.com/category/3082"

# add [-o] flag for not printing to file.
# flag for read html
# send stderr to tresh
# --base=${base_url}
data=$(wget --no-check-certificate --output-file=-  $site 2>/dev/null)
re_site="https://ynetnews.com/article/[0-9A-Za-z]+"

grep -E -o $re_site  
